import { Anton } from "@next/font/google";
import "./globals.css";
import localFont from '@next/font/local'

const anton = Anton({   weight: ["400"],   
subsets: ["latin"],
variable: "--Anton-font",
family: "Anton",
});

const GothamBlack = localFont(
  { src: '../../public/GothamBlackRegular.ttf',
    family: 'GothamBlack' ,
    variable:'--GB-font',
    subsets: ["latin"],
  })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GothamBlack.variable}  ${anton.variable}   `}>{children}</body>
    </html>
  );
}
